### ISSUE TITLE
TypeError: `generator` yielded an element of shape (h, w, c) where an element of shape (w, h, c) was expected.

### ISSUE THREAD

**Issue by vinhill** [isarandi/tensorflow-inputs#1]
### Example
```
frame_paths = glob(f'/globalwork/datasets/3DPW/imageFiles/courtyard_arguing_00/image_*.jpg')
batches_gpu, batches_cpu = tfinp.image_files(frame_paths, batch_size=64, prefetch_gpu=2, tee_cpu=True)
batch_gpu, batch_cpu = next(iter(zip(batches_gpu, batches_cpu)))
```
### Expected behavior
One batch is fetched
### Actual behavior
An error occurs
> TypeError: `generator` yielded an element of shape (1920, 1080, 3) where an element of shape (1080, 1920, 3) was expected

### Reason
The [`image_files`](https://github.com/isarandi/tensorflow-inputs/blob/main/tensorflow_inputs/tensorflow_inputs.py#L23C53-L23C53) function passes `[width, height]` on as imshape, which is used for `output_shapes` with `Dataset.from_generator` while `cv2.imread` will return images as `[height, width, channels]`. MeTRAbs seems to [expect](https://github.com/isarandi/metrabs/blob/master/metrabs_tf/models/metrabs.py#L100) the input format as `[height, width]` thus `imshape` in `image_files` should probably change.

**Comment by isarandi** [comment]
Thanks for the detailed bug report, I just pushed a fix.
Let me know if you come across any other issues.

**Comment by isarandi** [comment]
As an aside, in your example code, make sure to sort the glob result, else you might get your frames out of order. (glob may not give alphabetically sorted results when the directory entries are not sorted on the file system).

**Comment by vinhill** [comment]
Ah thanks for the hint :)
